# Generated by Django 5.0.2 on 2024-02-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_table',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
